import { useRef, useState } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ArrowRight, BarChart3, Blocks, Bot, CheckCircle, ChevronRight, Cog, Copy, CreditCard, File, Key, Link2, Network, Play, Shield, ShoppingCart, Terminal, Upload, Wallet, Zap, Award } from "lucide-react";
import "./_group.css";

const snippets = {
  python: `import hashlib, requests

# 1. Hash your content locally — nothing leaves your machine
file_hash = hashlib.sha256(open("decision.md", "rb").read()).hexdigest()

# 2. Anchor — one API call, proof_id returned in ~1 second
proof = requests.post(
    "https://provebeforeact.com/api/proof",
    headers={"Authorization": "Bearer YOUR_PM_KEY"},
    json={"file_hash": file_hash, "filename": "decision.md"}
).json()
print(proof["verify_url"])  # → https://provebeforeact.com/proof/prf_...`,
  typescript: `import crypto from "crypto";
const content = await fs.readFile("decision.md");
const fileHash = crypto.createHash("sha256").update(content).digest("hex");
const proof = await fetch("https://provebeforeact.com/api/proof", {
  method: "POST", headers: { Authorization: "Bearer YOUR_PM_KEY" },
  body: JSON.stringify({ file_hash: fileHash, filename: "decision.md" }),
}).then(r => r.json());`,
  curl: `FILE_HASH=$(sha256sum decision.md | awk '{print $1}')
curl -s -X POST https://provebeforeact.com/api/proof \\
  -H "Authorization: Bearer YOUR_PM_KEY" \\
  -H "Content-Type: application/json" \\
  -d "{\\"file_hash\\": \\"$FILE_HASH\\", \\"filename\\": \\"decision.md\\"}"
# → "https://provebeforeact.com/proof/prf_..."`,
};
const noop = () => {};
const price = "$0.01";

function Header({ onConnect }: { onConnect: () => void }) {
  return <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur">
    <div className="container flex h-16 items-center justify-between gap-4">
      <a href="#top"><img src="/__mockup/pba-logo.svg" alt="Prove Before Act" className="h-8 w-auto" /></a>
      <nav className="hidden items-center gap-6 md:flex text-sm font-medium text-muted-foreground">
        <a href="#how-it-works">How it works</a><a href="#standard">Standard</a><button onClick={noop}>More ···</button>
        <a href="#free-trial" className="rounded-md border border-primary/20 bg-primary/10 px-3 py-1.5 text-primary">Start free</a>
      </nav>
      <div className="flex items-center gap-2 sm:gap-3"><a href="#zh" className="rounded-md border border-border/50 px-2.5 py-1.5 font-mono text-xs text-muted-foreground">中文</a><Button variant="ghost" size="sm" onClick={onConnect}><Wallet className="mr-2 h-4 w-4" />Connect</Button></div>
    </div>
  </header>;
}

function Footer() {
  return <footer className="border-t py-12"><div className="container"><div className="mx-auto grid max-w-5xl gap-8 md:grid-cols-4">
    <div className="md:col-span-2"><img src="/__mockup/pba-logo.svg" alt="Prove Before Act" className="mb-4 h-8 w-auto" /><p className="max-w-xs text-sm text-muted-foreground">The accountability pattern for agents that act in the world.</p></div>
    <div><h2 className="mb-4 text-sm font-semibold">Explore</h2><ul className="space-y-2 text-sm text-muted-foreground"><li>60-second overview</li><li>PBA Standard</li><li>For AI Agents</li><li>Trust Leaderboard</li><li>Metrics</li></ul></div>
    <div><h2 className="mb-4 text-sm font-semibold">Developers</h2><ul className="space-y-2 text-sm text-muted-foreground"><li>API Docs</li><li>Agent Context</li><li>MCP Server</li><li>Privacy</li><li>Terms</li></ul></div>
  </div><div className="mx-auto mt-10 flex max-w-5xl flex-col items-center justify-between gap-3 border-t pt-6 text-sm text-muted-foreground sm:flex-row"><span>© 2025 Prove Before Act</span><span>Powered by MultiversX</span></div></div></footer>;
}

function QuickStart() {
  const [language, setLanguage] = useState<keyof typeof snippets>("python");
  const [copied, setCopied] = useState(false);
  return <div className="rounded-md border border-border/60 overflow-hidden">
    <div className="flex items-center border-b border-border/60 bg-muted/30 px-1">{(Object.keys(snippets) as (keyof typeof snippets)[]).map(l => <button key={l} onClick={() => setLanguage(l)} className={`px-4 py-2 text-xs font-mono font-medium ${language === l ? "border-b-2 border-primary -mb-px text-foreground" : "text-muted-foreground"}`}>{l}</button>)}<div className="ml-auto flex gap-3 pr-2"><button className="text-xs text-primary">Get free key →</button><button onClick={() => setCopied(true)} className="flex items-center gap-1 text-xs text-muted-foreground"><Copy className="h-3.5 w-3.5" />{copied ? "Copied" : "Copy"}</button></div></div>
    <pre className="overflow-x-auto whitespace-pre bg-muted/20 p-4 text-xs leading-relaxed text-foreground/85">{snippets[language]}</pre>
  </div>;
}

export function Current() {
  const input = useRef<HTMLInputElement>(null);
  const [agentName, setAgentName] = useState("");
  const [key, setKey] = useState<string | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [connected, setConnected] = useState(false);
  const connect = () => setConnected(true);
  const register = () => { if (agentName.trim().length > 1) setKey("pm_live_9a7c3f4d8e2b1a6c"); };
  return <div id="top" className="pba-home min-h-screen bg-background">
    <Header onConnect={connect} />
    {connected && <div className="fixed inset-x-0 top-16 z-40 border-b border-primary/20 bg-card p-3 text-center text-sm"><CheckCircle className="mr-2 inline h-4 w-4 text-primary" />Wallet connection is stubbed for this static audit.</div>}
    <section className="container pt-14 pb-20 md:pt-20 md:pb-28"><div className="mx-auto max-w-5xl text-center">
      <div className="mb-5 flex justify-center"><Badge variant="outline" className="gap-1.5 px-3 py-1 text-xs"><Play className="h-3 w-3 text-primary" />Prove Before Act — the accountability pattern for autonomous agents</Badge></div>
      <h1 className="mb-3 text-4xl font-bold leading-tight tracking-tight sm:text-5xl md:text-6xl lg:text-7xl">Prove Before Act<br /><span className="text-primary">the accountability pattern<br />for autonomous agents.</span></h1>
      <p className="mx-auto mb-8 max-w-2xl text-lg leading-relaxed text-muted-foreground md:text-xl">Commit an independently verifiable decision basis before your agent acts. {price}/proof · 10 free certs · no wallet needed.</p>
      <div className="flex flex-col justify-center gap-4 sm:flex-row"><Button size="lg" className="h-12 px-8 text-base" asChild><a href="#free-trial"><Bot className="mr-2 h-4 w-4" />I run an agent or service</a></Button><Button size="lg" variant="outline" className="h-12 px-8 text-base"><Upload className="mr-2 h-5 w-5" />I need to verify a file</Button></div>
      <p className="mt-3 text-sm text-muted-foreground">New to Prove Before Act? <a href="#learn" className="underline">60-second overview →</a></p><p className="mt-3 font-mono text-sm text-muted-foreground">Register free → Get key → First proof in 1 curl</p>
      <p className="mt-2 text-xs text-muted-foreground">xProof is the reference implementation of the <a href="#standard" className="underline">Prove Before Act specification</a></p>
      <div className="mt-6 flex justify-center"><div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/5 px-4 py-1.5 text-sm"><Zap className="h-3.5 w-3.5 shrink-0 text-primary" /><span className="text-muted-foreground">No API key needed — anchor + pay via <strong className="text-foreground">x402</strong> · one HTTP request · USDC on Base</span></div></div>
    </div></section>
    <section id="free-trial" className="border-y bg-muted/30 py-16 md:py-20"><div className="container"><div className="mx-auto max-w-2xl text-center">
      <Badge variant="secondary" className="mb-4 px-3 py-1"><Key className="mr-2 h-3.5 w-3.5" />Free Trial — No wallet needed</Badge><h2 className="mb-3 text-2xl font-bold md:text-3xl">10 free proofs. Start in 30 seconds.</h2><p className="mx-auto mb-8 max-w-xl text-muted-foreground">Register your agent or project — get a <code className="rounded bg-muted px-1.5 py-0.5 text-xs">pm_</code> API key instantly. No wallet, no credit card.</p>
      {!key ? <div className="mx-auto max-w-md"><div className="flex flex-col gap-3 sm:flex-row"><Input value={agentName} onChange={e => setAgentName(e.target.value)} onKeyDown={e => e.key === "Enter" && register()} placeholder="Agent name (e.g. my-agent)" /><Button onClick={register} disabled={agentName.trim().length < 2}>Get my key <ArrowRight className="ml-2 h-4 w-4" /></Button></div><div className="mt-6 flex flex-wrap justify-center gap-2">{["10 free proofs","No wallet needed","No credit card","Claim to wallet anytime"].map(x => <Badge key={x} variant="outline" className="text-xs">{x}</Badge>)}</div></div> :
      <div className="mx-auto max-w-lg"><div className="mb-2 flex gap-2 rounded-md border border-primary/20 bg-primary/10 p-3 font-mono text-sm text-primary">{key}<Button size="icon" variant="ghost"><Copy className="h-4 w-4" /></Button></div><p className="mb-5 text-sm text-muted-foreground">Your key is ready — 10 free proofs for <strong>{agentName}</strong>. Try one right now:</p>
      <div onClick={() => input.current?.click()} className="cursor-pointer rounded-md border-2 border-dashed border-muted-foreground/30 p-7 text-center"><input ref={input} type="file" className="hidden" onChange={e => setFile(e.target.files?.[0] || null)} />{file ? <><File className="mx-auto mb-3 h-7 w-7 text-primary" /><p className="text-sm font-medium">{file.name}</p><p className="mt-1 font-mono text-xs text-muted-foreground">c9a3b61e76d9b0d4a5e2…</p></> : <><Upload className="mx-auto mb-3 h-7 w-7 text-muted-foreground/50" /><p className="text-sm font-medium text-muted-foreground">Select an output, decision log, data snapshot, or build artifact</p><p className="mt-1 text-xs text-muted-foreground/60">Only the SHA-256 hash is transmitted — source data stays in this runtime</p></>}</div>{file && <Button className="mt-3 w-full"><Shield className="mr-2 h-4 w-4" />Anchor this proof</Button>}<div className="mt-5"><Button variant="outline" size="sm">Fleet integration guide <ArrowRight className="ml-1 h-3 w-3" /></Button><Button variant="ghost" size="sm" onClick={connect}><Wallet className="mr-2 h-3.5 w-3.5" />Connect wallet</Button></div></div>}
    </div></div></section>
    <section className="py-16 md:py-20"><div className="container"><div className="mx-auto max-w-3xl"><div className="mb-8 text-center"><Badge variant="outline" className="mb-4">Quick Start</Badge><h2 className="mb-2 text-2xl font-bold md:text-3xl">Integrate in 2 minutes</h2><p className="text-sm text-muted-foreground">Copy-paste ready. Python · TypeScript · curl.</p></div><QuickStart /><div className="mt-6 grid gap-3 md:grid-cols-3">{[[Cog,"REST API","POST a SHA-256 hash with your pm_ key.","Full docs"],[Bot,"MCP / x402","No account needed. Discover, pay, anchor — one session.","Agent guide"],[Upload,"Web UI","Connect wallet, drag a file, get a proof. No code.","Connect wallet"]].map(([Icon,title,desc,action]) => { const I = Icon as typeof Cog; return <div key={title as string} className="rounded-md border bg-muted/20 p-4"><div className="mb-2 flex items-center gap-2"><I className="h-4 w-4 text-primary" /><span className="text-sm font-semibold">{title as string}</span></div><p className="mb-3 text-xs text-muted-foreground">{desc as string}</p><Button variant="outline" size="sm">{action as string} <ArrowRight className="ml-1 h-3 w-3" /></Button></div>})}</div></div></div></section>
    <section className="border-y bg-muted/20 py-12 md:py-16"><div className="container"><div className="mx-auto max-w-4xl"><p className="mb-8 text-center text-xs font-semibold uppercase tracking-widest text-muted-foreground">MultiversX Machine Economy Stack</p><div className="hidden items-stretch sm:flex">{[["MX-8004","Identity","Who is the agent?"],["AP2","Authority","Is it authorised?"],["MCP","Communication","What did it request?"],["x402","Payments","What did it pay?"],["Prove Before Act","Verifiable Intent","Why did it act?"]].map(([id,label,desc],i)=><div key={id} className="flex flex-1 items-center">{i>0&&<ChevronRight className="mx-1 h-4 w-4 text-muted-foreground/30" />}<div className={`flex h-full flex-1 flex-col items-center rounded-md border px-3 py-5 text-center ${i===4?"border-primary bg-primary/5":"bg-background/60"}`}><span className={`font-mono text-sm font-bold ${i===4?"text-primary":""}`}>{id}</span><span className="mt-1 text-xs font-semibold text-muted-foreground">{label}</span><span className="mt-1.5 text-xs text-muted-foreground/70">{desc}</span></div></div>)}</div><p className="mt-8 text-center text-sm text-muted-foreground">Prove Before Act is the accountability pattern. <strong className="text-foreground">xProof is its reference implementation for independently verifiable evidence.</strong></p></div></div></section>
    <section id="standard" className="border-t py-16 md:py-20"><div className="container"><div className="mx-auto max-w-5xl"><div className="mb-10 text-center"><Badge variant="outline" className="mb-4">Use cases</Badge><h2 className="mb-2 text-2xl font-bold md:text-3xl">One pattern, every agent type</h2><p className="text-sm text-muted-foreground">Hash → anchor → act. The same loop works for trading, research, support, and orchestration fleets.</p></div><div className="grid gap-4 md:grid-cols-2">{[[BarChart3,"Trading Agent","High value","RSI=38, risk approved"],[Terminal,"Research Agent","Attribution","12 peer-reviewed sources"],[Zap,"Customer Support Agent","Compliance","model: gpt-4o"],[Network,"Multi-agent Orchestration","Fleet","Batch: up to 100 actions per call"]].map(([Icon,title,badge,line])=>{const I=Icon as typeof Bot;return <div key={title as string} className="rounded-md border bg-muted/20 p-5"><div className="mb-1 flex gap-2"><I className="h-4 w-4 text-primary" /><span className="text-sm font-bold">{title as string}</span><Badge variant="secondary" className="ml-auto text-xs">{badge as string}</Badge></div><p className="mb-3 text-xs text-muted-foreground">Prove the declared decision basis behind every action <em>before</em> execution — an independently verifiable audit trail.</p><pre className="overflow-x-auto rounded border border-border/40 bg-muted/60 p-3 text-xs">{`# Anchor before execution\nproof = xproof.certify(\n  metadata={"why": "${line}"}\n)`}</pre></div>})}</div></div></div></section>
    <section id="how-it-works" className="border-y bg-muted/30 py-20 md:py-28"><div className="container"><div className="mx-auto max-w-5xl"><div className="mb-16 text-center"><Badge variant="outline" className="mb-4">How it works</Badge><h2 className="mb-4 text-3xl font-bold md:text-4xl">One API call. Permanent accountability.</h2><p className="mx-auto max-w-2xl text-lg text-muted-foreground">Integrate Prove Before Act into your agent's execution loop. Every decision, output, and action becomes a verifiable on-chain record.</p></div><div className="grid gap-8 md:grid-cols-3">{[["Your agent acts","Your agent makes a decision, produces an output, or executes a task. Before moving on, it hashes that action locally — nothing leaves your infrastructure."],["POST the SHA-256 hash","One API call with a SHA-256 hash and optional metadata — model version, strategy, confidence level, session ID."],["Proof anchored on-chain","Prove Before Act anchors the hash on MultiversX and returns a proof_id and blockchain transaction URL."]].map(([title,text],i)=><div key={title}><div className="mb-6 flex h-16 w-16 items-center justify-center rounded-full bg-primary text-2xl font-bold text-primary-foreground">{i+1}</div><h3 className="mb-3 text-xl font-semibold">{title}</h3><p className="text-muted-foreground">{text}</p></div>)}</div></div></div></section>
    <section id="pricing" className="border-y bg-muted/30 py-20 md:py-28"><div className="container"><div className="mx-auto max-w-3xl"><div className="mb-12 text-center"><Badge variant="outline" className="mb-4">Simple pricing</Badge><h2 className="mb-4 text-3xl font-bold md:text-4xl">One price. No subscription.</h2><p className="text-lg text-muted-foreground">Pay only for what you use. No hidden fees, no commitment.</p></div><Card className="mx-auto max-w-md border-primary shadow-lg"><CardContent className="pt-8 pb-8"><div className="mb-6 text-center"><span className="text-5xl font-bold">{price}</span><p className="text-muted-foreground">per proof</p><p className="mt-1 text-xs text-muted-foreground">Flat rate. No tiers, no subscription.</p></div><ul className="mb-8 space-y-3 text-sm">{["Unlimited proofs","Public proof_id and blockchain transaction URL","Public verification page","Optional PDF export with QR shortcut","MultiversX blockchain"].map(x=><li key={x} className="flex gap-2"><CheckCircle className="h-4 w-4 shrink-0 text-primary" />{x}</li>)}</ul><Button className="w-full" size="lg" onClick={connect}>Get started</Button></CardContent></Card><p className="mt-8 text-center text-sm text-muted-foreground">Payment in $EGLD or USDC.</p></div></div></section>
    <section id="integrations" className="py-20 md:py-28"><div className="container"><div className="mx-auto max-w-5xl"><div className="mb-16 text-center"><Badge variant="outline" className="mb-4">Universal compatibility</Badge><h2 className="mb-4 text-3xl font-bold md:text-4xl">Works everywhere agents work.</h2><p className="text-lg text-muted-foreground">One proof layer, every protocol. From autonomous agents to CI/CD pipelines.</p></div><div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6">{[[Blocks,"MCP","Model Context Protocol"],[CreditCard,"x402","HTTP-native payments"],[ShoppingCart,"ACP","Agent Commerce"],[Award,"MX-8004","Trustless Agents"],[Bot,"OpenClaw","Skill Marketplace"],[Cog,"GitHub Action","CI/CD Pipeline"]].map(([Icon,name,desc])=>{const I=Icon as typeof Bot;return <Card key={name as string} className="text-center"><CardContent className="pt-6 pb-4"><div className="mx-auto mb-3 flex h-10 w-10 items-center justify-center rounded-full bg-primary/10"><I className="h-5 w-5 text-primary" /></div><p className="text-sm font-semibold">{name as string}</p><p className="mt-1 text-xs text-muted-foreground">{desc as string}</p></CardContent></Card>})}</div></div></div></section>
    <section id="x402" className="border-y bg-muted/30 py-20 md:py-28"><div className="container"><div className="mx-auto max-w-5xl"><div className="mb-16 text-center"><Badge variant="outline" className="mb-4">Base Network · x402</Badge><h2 className="mb-4 text-3xl font-bold md:text-4xl">Agents pay natively.<br />No signup, no API key.</h2><p className="text-lg text-muted-foreground">Any x402-compatible agent anchors proofs in one round-trip. The current rate is {price} in USDC on Base. No account required.</p></div><div className="grid gap-4 md:grid-cols-3">{[["Submit proof","# No API key, no auth\nPOST https://provebeforeact.com/api/proof\n{ \"file_hash\": \"sha256...\" }"],["Receive payment challenge","HTTP 402 Payment Required\n{ \"price\": \"$0.01\", \"network\": \"eip155:8453\", \"asset\": \"USDC\" }"],["Pay & get proof","# Retry with USDC payment\nX-Payment: eyJ...\nHTTP 200 OK\n{ \"proof_id\": \"prf_...\" }"]].map(([title,code],i)=><div key={title}><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-sm font-bold text-primary-foreground">{i+1}</div><h3 className="font-semibold">{title}</h3></div><p className="my-3 pl-11 text-sm text-muted-foreground">Agent {i===0?"sends a POST with no credentials.":i===1?"receives payment terms on Base.":"retries with payment receipt — gets blockchain proof."}</p><pre className="overflow-x-auto rounded-md bg-[#0d1117] p-4 font-mono text-xs leading-relaxed text-[#e6edf3]">{code}</pre></div>)}</div></div></div></section>
    <section id="faq" className="py-20 md:py-28"><div className="container"><div className="mx-auto max-w-3xl"><div className="mb-12 text-center"><Badge variant="outline" className="mb-4">FAQ</Badge><h2 className="text-3xl font-bold md:text-4xl">Frequently asked questions</h2></div><Accordion type="single" collapsible>{[["Is my file uploaded to your servers?","No. Only the SHA-256 hash is transmitted. Source data never leaves the agent's runtime environment."],["What is the MultiversX blockchain?","MultiversX is a high-performance, eco-friendly European blockchain: a global public ledger impossible to modify or delete."],["Does it have legal value?","Blockchain timestamping is recognized in many jurisdictions as proof of prior existence."],["What happens if I modify my file?","The slightest change generates a completely different SHA-256 hash, guaranteeing integrity."],["How can someone verify my proof?","Each proof has a public proof_id and blockchain transaction URL."],["Why do I need a crypto wallet?","The wallet securely identifies you and signs your proofs like an ultra-secure electronic signature."]].map(([q,a],i)=><AccordionItem value={`item-${i}`} key={q}><AccordionTrigger className="text-left">{q}</AccordionTrigger><AccordionContent className="text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></div></section>
    <section className="border-t bg-primary/5 py-20 md:py-28"><div className="container"><div className="mx-auto max-w-3xl text-center"><h2 className="mb-4 text-3xl font-bold md:text-4xl">Start anchoring trust</h2><p className="mb-8 text-lg text-muted-foreground">Verifiable proofs for developers, agents, and enterprises. {price} per proof.</p><div className="flex flex-col justify-center gap-4 sm:flex-row"><Button size="lg" className="h-12 px-8 text-base"><Key className="mr-2 h-5 w-5" />Start free — no wallet</Button><Button size="lg" variant="outline" className="h-12 px-8 text-base" onClick={connect}><Shield className="mr-2 h-5 w-5" />Connect wallet</Button></div></div></div></section>
    <Footer />
  </div>;
}