// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pba-home-audit/Current.tsx": () => import("../components/mockups/pba-home-audit/Current.tsx"),
  "./components/mockups/pba-home-audit/PremiumAccountability.tsx": () => import("../components/mockups/pba-home-audit/PremiumAccountability.tsx")
};
